/**
 * Askpass relay — lets sudo / git / ssh password prompts inside an agent's
 * shell reach the phone instead of hanging (or failing) on a TTY nobody has.
 *
 * sudo falls back to `$SUDO_ASKPASS` automatically when it has no terminal
 * (verified with sudo 1.9); git honours `$GIT_ASKPASS`; ssh honours
 * `$SSH_ASKPASS` when `SSH_ASKPASS_REQUIRE=force`. All three run the helper
 * with the prompt as its argument and read the secret from its stdout.
 *
 * The helper is generated into the bridge data dir (never the repo), calls
 * `POST /api/askpass` on the loopback bridge, and prints whatever the user
 * typed on the phone. The secret is never logged or stored — see
 * routes/askpass.ts.
 */

import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { getConfig } from '../config.js';
import { getRunModeInfo } from '../runMode.js';
import { resolveBridgeDataDir } from '../mcp/hostPaths.js';
import { childLogger } from '../log.js';

const log = childLogger('askpass');

const HELPER_JS = `#!/usr/bin/env node
// Generated by AgentVoice — relays a password prompt to the phone. Do not edit.
const url = process.env.AGENTVOICE_BRIDGE_URL;
const token = process.env.AGENTVOICE_ASKPASS_TOKEN;
const prompt = process.argv.slice(2).join(' ').trim() || 'Password:';
if (!url || !token) {
  process.stderr.write('agentvoice askpass: bridge not configured\\n');
  process.exit(1);
}
try {
  const res = await fetch(url.replace(/\\/$/, '') + '/api/askpass', {
    method: 'POST',
    headers: { authorization: 'Bearer ' + token, 'content-type': 'application/json' },
    body: JSON.stringify({ prompt }),
    signal: AbortSignal.timeout(290_000),
  });
  if (!res.ok) {
    process.stderr.write('agentvoice askpass: ' + res.status + ' ' + (await res.text()).slice(0, 200) + '\\n');
    process.exit(1);
  }
  const body = await res.json();
  if (typeof body.secret !== 'string') {
    process.stderr.write('agentvoice askpass: cancelled on the phone\\n');
    process.exit(1);
  }
  process.stdout.write(body.secret + '\\n');
} catch (err) {
  process.stderr.write('agentvoice askpass: ' + (err && err.message ? err.message : String(err)) + '\\n');
  process.exit(1);
}
`;

let cachedEnv: NodeJS.ProcessEnv | null = null;

function writeIfChanged(path: string, content: string, mode: number): void {
  const current = existsSync(path) ? readFileSync(path, 'utf8') : null;
  if (current !== content) writeFileSync(path, content, { mode });
  chmodSync(path, mode);
}

/**
 * Environment additions for every agent child process. Generates the helper
 * on first use; failures are logged and leave the env untouched, so a broken
 * data dir never blocks a spawn.
 */
export function askpassEnv(): NodeJS.ProcessEnv {
  if (cachedEnv) return cachedEnv;
  try {
    const dir = resolveBridgeDataDir();
    mkdirSync(dir, { recursive: true });
    const helperJs = join(dir, 'askpass.mjs');
    const helperSh = join(dir, 'askpass.sh');
    writeIfChanged(helperJs, HELPER_JS, 0o755);
    // sudo/git/ssh exec the helper directly; a shell wrapper pins the node the
    // bridge runs on so PATH inside the agent's shell does not matter.
    writeIfChanged(
      helperSh,
      `#!/bin/sh\n# Generated by AgentVoice — see src/executor/askpass.ts\nexec ${shellQuote(process.execPath)} ${shellQuote(helperJs)} "$@"\n`,
      0o755,
    );

    const { env, settings } = getConfig();
    cachedEnv = {
      SUDO_ASKPASS: helperSh,
      GIT_ASKPASS: helperSh,
      SSH_ASKPASS: helperSh,
      SSH_ASKPASS_REQUIRE: 'force',
      AGENTVOICE_BRIDGE_URL: getRunModeInfo(settings).backendUrl,
      AGENTVOICE_ASKPASS_TOKEN: env.APP_TOKEN,
    };
    log.debug({ helper: helperSh }, 'askpass helper ready');
    return cachedEnv;
  } catch (err) {
    log.warn({ err: err instanceof Error ? err.message : String(err) }, 'askpass helper unavailable');
    return {};
  }
}

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}
