/**
 * `agentvoice token` — show the pairing token, or mint a new one.
 *
 * The token goes to stdout on its own line and everything else goes to stderr,
 * so `agentvoice token | pbcopy` does the obvious thing. This is the only
 * command in the CLI that is allowed to print it; `status` and `doctor` report
 * it as configured or not.
 *
 * Rotation rewrites `<home>/.env` in place at mode 0600, preserving every other
 * line: .env also holds AWS keys and provider credentials, and losing those to
 * a token rotation would be an unpleasant surprise.
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { envPath, newToken, readEnvFile, resolveHome } from '../home.js';
import { bold, dim, fail, note, say, yellow } from '../out.js';

export function tokenCommand(opts: { rotate: boolean }): number {
  const home = resolveHome();
  const path = envPath(home);

  if (!opts.rotate) {
    const fromFile = (readEnvFile(home).get('APP_TOKEN') ?? '').trim();
    if (fromFile) {
      note(dim(`from ${path}`));
      say(fromFile);
      return 0;
    }
    const fromEnv = (process.env['APP_TOKEN'] ?? '').trim();
    if (fromEnv) {
      note(dim('from APP_TOKEN in the environment'));
      say(fromEnv);
      return 0;
    }
    fail(
      `no APP_TOKEN configured.\n` +
        `  Expected it in ${path}, or as an APP_TOKEN environment variable.\n` +
        '  Create one:  agentvoice token --new',
    );
    return 1;
  }

  const token = newToken();
  writeFileSync(path, replaceToken(path, token), { mode: 0o600 });

  note('');
  note(`  ${bold('New APP_TOKEN written to')} ${path}`);
  note('');
  say(token);
  note('');
  note(`  ${yellow('Every paired client is now locked out.')} Re-pair each phone and browser`);
  note('  with the token above, then restart the bridge so it loads the new value:');
  note('');
  note('    agentvoice restart        # or `agentvoice run` if you have no service');
  note('');
  if ((process.env['APP_TOKEN'] ?? '').trim()) {
    note(`  ${yellow('Note:')} APP_TOKEN is also set in your environment, and that wins over`);
    note('  the .env file. Unset it, or the bridge will keep using the old value.');
    note('');
  }
  return 0;
}

/**
 * Swap the APP_TOKEN line, leaving comments, ordering and every other key
 * exactly as they were. Appends when the file has no APP_TOKEN yet.
 */
function replaceToken(path: string, token: string): string {
  const existing = existsSync(path) ? readFileSync(path, 'utf8') : '';
  let replaced = false;

  const lines = existing.split('\n').map((line) => {
    if (!/^\s*APP_TOKEN\s*=/.test(line)) return line;
    replaced = true;
    return `APP_TOKEN=${token}`;
  });

  if (!replaced) {
    if (lines.length && lines[lines.length - 1] !== '') lines.push('');
    lines.push('# Generated by `agentvoice token --new`. Keep it secret.');
    lines.push(`APP_TOKEN=${token}`);
    lines.push('');
  }

  return lines.join('\n').replace(/\n*$/, '\n');
}
